### ISSUE TITLE
pgConfig change breaks production config

### ISSUE THREAD

**Issue by WanderingStar** [Data4Democracy/internal-displacement#138]
This code in `master` breaks production:
```
//if not using docker
//create a pgConfig.js file in the same directory and put your credentials there
const connectionObj = require('./pgConfig');
```

```
nodejs_1   | [0] Error: Cannot find module './pgConfig'
nodejs_1   | [0]     at Function.Module._resolveFilename (module.js:470:15)
nodejs_1   | [0]     at Function.Module._load (module.js:418:25)
nodejs_1   | [0]     at Module.require (module.js:498:17)
nodejs_1   | [0]     at require (internal/module.js:20:19)
nodejs_1   | [0]     at Object.<anonymous> (/internal-displacement-web/server/pgDB/index.js:5:23)
nodejs_1   | [0]     at Module._compile (module.js:571:32)
nodejs_1   | [0]     at Object.Module._extensions..js (module.js:580:10)
nodejs_1   | [0]     at Module.load (module.js:488:32)
nodejs_1   | [0]     at tryModuleLoad (module.js:447:12)
nodejs_1   | [0]     at Function.Module._load (module.js:439:3)
nodejs_1   | [0] [nodemon] app crashed - waiting for file changes before starting...
```

Can this be made optional? If the file `pgConfig` exists, require it, otherwise use the environment variables?

**Comment by wwymak** [comment]
updated that -- there's 2 options now in the npm scripts so if you use `npm run start-localDB` it runs the pgconfig file otherwise it looks for the db opts in the process.env variables

**Comment by WanderingStar** [comment]
Great, thanks!
